import { useState, useEffect } from 'react'
import { AI_AVATARS } from '../components/AiAvatarSelector.jsx'

const VIDEO_FILES = [
  { id: 'video1', title: 'Introduction to Investing', subtitle: 'Why investing matters for your financial future', category: 'FINANCIAL FOUNDATIONS', duration: '3:45', src: '/videos/video1.mp4',
    takeaways: [
      { term: 'Investment', def: '🌱 Like planting a seed that grows into a big Money Tree! You put savings away, and it grows bigger over time.' },
      { term: 'Interest', def: '🎁 Free bonus cash! The bank rewards you for keeping your money safe with them.' },
      { term: 'Risk', def: '🎢 The rollercoaster ride! Markets move up and down, so smart investors stay balanced.' },
      { term: 'Returns', def: '🍎 The sweet apples you harvest! This is the profit generated by your investment.' },
    ]
  },
  { id: 'video2', title: 'Understanding Financial Literacy', subtitle: 'Building smart money habits & financial awareness', category: 'MONEY MANAGEMENT', duration: '4:20', src: '/videos/video2.mp4',
    takeaways: [
      { term: 'Financial Literacy', def: '📚 Understanding how money works and making confident, informed financial choices.' },
      { term: 'Budgeting', def: '📊 Planning your income so you systematically save before spending on wants.' },
      { term: 'Emergency Fund', def: '🛡️ Your financial safety net! 3 to 6 months of expenses saved for unexpected rainy days.' },
      { term: 'Cash Flow', def: '💸 Tracking your monthly income stream versus total outgoing expenses.' },
    ]
  },
  { id: 'video3', title: 'Introduction to Financial Terms', subtitle: 'Key terminology: Stocks, Mutual Funds & Compound Growth', category: 'MARKET ESSENTIALS', duration: '5:15', src: '/videos/video3.mp4',
    takeaways: [
      { term: 'SIP', def: '🗓️ Systematic Investment Plan! Depositing fixed amounts monthly to build wealth effortlessly.' },
      { term: 'Mutual Fund', def: '🧺 A professionally managed basket pooling money from thousands of investors.' },
      { term: 'NAV', def: '🏷️ Net Asset Value — the daily market price tag for one unit of a mutual fund.' },
      { term: 'Compounding', def: '❄️ The compounding snowball! Earning interest on top of accumulated interest.' },
    ]
  },
  { id: 'video4', title: 'Tax Saving Schemes & Terms', subtitle: 'Maximizing returns with 80C, PPF & ELSS tax benefits', category: 'TAX & SAVINGS', duration: '4:50', src: '/videos/video4.mp4',
    takeaways: [
      { term: 'Section 80C', def: '🛡️ Key income tax provision offering tax deductions up to ₹1.5 Lakh annually.' },
      { term: 'PPF', def: '🏦 Public Provident Fund — 15-year government scheme with guaranteed tax-free interest.' },
      { term: 'ELSS', def: '🚀 Equity Linked Savings Scheme — tax-saving mutual funds with potential high market returns.' },
      { term: 'EEE Status', def: '✨ Exempt-Exempt-Exempt! Zero tax payable on deposit, interest, and final maturity.' },
    ]
  },
  { id: 'video5', title: 'Smart Asset Allocation & Planning', subtitle: 'Balancing risk, returns and building a secure future', category: 'STRATEGIC PLANNING', duration: '6:10', src: '/videos/video5.mp4',
    takeaways: [
      { term: 'Asset Allocation', def: '⚖️ Distributing money across Debt, Equity, FDs, and Gold to balance safety and growth.' },
      { term: 'Liquidity', def: '💧 How quickly an asset can be converted back into spendable cash without loss.' },
      { term: 'Inflation', def: '🎈 The gradual rise in prices over time that reduces your money\'s purchasing power.' },
      { term: 'Wealth Creation', def: '🏆 Long-term disciplined investing strategy to achieve true financial independence.' },
    ]
  },
]

function TakeawayModal({ video, onClose }) {
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  const emojiMap = {
    'Investment': '🌱', 'Interest': '🎁', 'Risk': '🎢', 'Returns': '🍎',
    'SIP': '🗓️', 'Mutual Fund': '🧺', 'NAV': '🏷️', 'Diversification': '🍭',
    'Fixed Deposit': '🔒', 'PPF': '🏰', 'Compounding': '❄️', 'Liquidity': '💧',
    'Equity': '🎫', 'Market Cap': '🏷️', 'Dividend': '🍰', 'Bull/Bear Market': '🐂',
    'Section 80C': '🛡️', 'TDS': '✂️', 'ELSS': '🚀', 'EEE Status': '✨'
  };

  return (
    <div style={{
      position:'fixed',inset:0,background:'rgba(8, 7, 5, 0.85)',
      zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',
      padding:20,backdropFilter:'blur(12px)',
      fontFamily: "'Space Grotesk', sans-serif",
    }} onClick={onClose}>
      <div className="glass-card-deep" style={{
        borderRadius:20, overflow:'hidden',
        maxWidth:520,width:'100%',
        background: 'var(--bg-card-deep, #12100c)',
        border: `2px solid #d97706`,
        animation: 'scaleIn 0.25s ease both',
        boxShadow: `var(--card-shadow, 0 20px 40px rgba(0,0,0,0.8))`,
        color: 'var(--text-main, #fef3c7)'
      }} onClick={e=>e.stopPropagation()}>
        <div style={{
          padding:'18px 24px',
          background: 'linear-gradient(135deg, #d97706 0%, #f59e0b 100%)',
          color: '#080705',
          display:'flex',justifyContent:'space-between',alignItems:'center',
        }}>
          <div style={{ fontWeight:900,fontSize:17,display:'flex',alignItems:'center',gap:8,textTransform:'uppercase' }}>
            <span>🌟</span> INVEST CLUB: KEY TAKEAWAYS!
          </div>
          <button onClick={onClose} style={{
            background:'#080705',border:'none',borderRadius:8,
            width: 28, height: 28, display: 'flex', alignItems: 'center', justifyContent: 'center',
            color:'#fbbf24',cursor:'pointer',fontWeight:900,fontSize: 14,
          }}>✕</button>
        </div>
        <div style={{ padding:24, background:'var(--bg-card-deep, #12100c)' }}>
          <p style={{ fontSize:14,color:'var(--gold-amber, #fbbf24)',marginBottom:16,fontWeight:800,textAlign:'center' }}>
            🎉 MASTER THESE KEY LESSON TERMS:
          </p>
          <div style={{ display:'flex',flexDirection:'column',gap:12, maxHeight:'340px', overflowY:'auto', paddingRight:6 }}>
            {video.takeaways.map((t,i)=>(
              <div key={i} style={{
                background: 'var(--bg-card, rgba(255,255,255,0.04))',
                borderRadius:14, padding:'14px 16px',
                border:`1.5px solid var(--border-light, rgba(217, 119, 6, 0.3))`,
                display:'flex', gap:12, alignItems:'flex-start',
              }}>
                <div style={{ fontSize:26, marginTop:2 }}>{emojiMap[t.term] || '⭐'}</div>
                <div>
                  <div style={{ fontWeight:900,color:'var(--heading-color, #ffffff)',fontSize:15,marginBottom:3 }}>
                    {t.term}
                  </div>
                  <div style={{ fontSize:13,color:'var(--text-sub, #d1d5db)',fontWeight:600,lineHeight:1.4 }}>
                    {t.def}
                  </div>
                </div>
              </div>
            ))}
          </div>
          <button onClick={onClose} className="btn-primary" style={{ width:'100%',marginTop:20,background:'linear-gradient(135deg, #d97706, #f59e0b)',color:'#080705' }}>
            GOT IT! BACK TO CLASSROOM 🚀
          </button>
        </div>
      </div>
    </div>
  )
}

const LessonGraphic = ({ id }) => {
  switch (id) {
    case 'video1': // Intro to Investing
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <line x1="12" y1="20" x2="12" y2="10" />
          <line x1="18" y1="20" x2="18" y2="4" />
          <line x1="6" y1="20" x2="6" y2="16" />
          <path d="M4 12l5-5 4 4 7-7" />
          <polyline points="16 4 20 4 20 8" />
        </svg>
      )
    case 'video2': // Financial Literacy
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#38bdf8" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <rect x="3" y="4" width="18" height="16" rx="2" />
          <line x1="3" y1="10" x2="21" y2="10" />
          <line x1="7" y1="15" x2="11" y2="15" />
          <circle cx="16.5" cy="15" r="1" fill="#38bdf8" />
        </svg>
      )
    case 'video3': // Financial Terms
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <path d="M3 3v18h18" />
          <path d="M18 9l-5 5-4-4-5 5" />
          <circle cx="18" cy="9" r="2" fill="#10b981" />
        </svg>
      )
    case 'video4': // Tax Saving Schemes
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
          <path d="M9 12l2 2 4-4" />
        </svg>
      )
    case 'video5': // Asset Allocation
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#a855f7" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="9" />
          <path d="M12 3v9h9" />
          <path d="M12 12L5.6 18.4" />
        </svg>
      )
    default:
      return (
        <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="1.8">
          <polygon points="5 3 19 12 5 21 5 3" />
        </svg>
      )
  }
}

function VideoCard({ v, watched, onWatch, delay = 1, activeAvatar, guideName }) {
  const [showPlayer, setShowPlayer] = useState(false)
  const [showTakeaway, setShowTakeaway] = useState(false)
  const [canMarkWatched, setCanMarkWatched] = useState(false)
  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && showPlayer) {
        setShowPlayer(false)
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [showPlayer])

  const isDraft = !v.src || v.src.includes('README.md') || v.src.includes('draft')

  const handleOpenPlayer = () => {
    setShowPlayer(true)
    setCanMarkWatched(isDraft)
  }

  const handleTimeUpdate = (e) => {
    const videoElem = e.target
    if (videoElem.duration && (videoElem.currentTime / videoElem.duration >= 0.85)) {
      setCanMarkWatched(true)
    }
  }

  const handleVideoEnd = () => {
    setCanMarkWatched(true)
  }

  const handleMarkWatched = () => {
    onWatch(v.id)
    setShowPlayer(false)
    setShowTakeaway(true)
  }

  const BG_GRADIENTS = {
    video1: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 60%, #0284c7 100%)',
    video2: 'linear-gradient(135deg, #064e3b 0%, #022c22 60%, #0d9488 100%)',
    video3: 'linear-gradient(135deg, #311042 0%, #180928 60%, #9333ea 100%)',
    video4: 'linear-gradient(135deg, #451a03 0%, #1c0d02 60%, #d97706 100%)',
    video5: 'linear-gradient(135deg, #4c0519 0%, #1f020a 60%, #e11d48 100%)',
  }

  const ACCENT_COLORS = {
    video1: '#38bdf8',
    video2: '#34d399',
    video3: '#c084fc',
    video4: '#fbbf24',
    video5: '#fb7185',
  }

  const accentColor = ACCENT_COLORS[v.id] || '#f59e0b'

  return (
    <>
      <div
        className={`glass-card-sm anim-fade delay-${delay}`}
        onClick={handleOpenPlayer}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{
          padding: '14px',
          background: 'var(--bg-card-deep, #12100c)',
          border: `1.5px solid ${watched ? '#10b981' : 'rgba(255, 255, 255, 0.15)'}`,
          cursor: 'pointer',
          borderRadius: 20,
          transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
          boxShadow: hovered 
            ? `0 16px 36px ${accentColor}33` 
            : 'var(--card-shadow, 0 6px 18px rgba(0,0,0,0.4))',
          transform: hovered ? 'translateY(-4px)' : 'none',
          display: 'flex', flexDirection: 'column', justifyContent: 'space-between'
        }}
      >
        <div>
          {/* Executive Video Thumbnail Container */}
          <div style={{
            width: '100%', height: 135, borderRadius: 14, marginBottom: 12,
            background: BG_GRADIENTS[v.id] || 'linear-gradient(135deg, #1e1b18, #0f172a)',
            position: 'relative',
            overflow: 'hidden',
            border: `1.5px solid ${watched ? '#10b981' : 'rgba(255, 255, 255, 0.15)'}`,
            boxShadow: '0 8px 24px rgba(0,0,0,0.6)',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
          }}>
            {/* Ambient Grid Overlay */}
            <div style={{
              position: 'absolute', inset: 0, opacity: 0.15,
              backgroundImage: `radial-gradient(${accentColor} 1px, transparent 1px)`,
              backgroundSize: '14px 14px', pointerEvents: 'none'
            }} />

            {/* Sleek Top Bar with Category & Duration */}
            <div style={{
              position: 'absolute', top: 8, left: 8, right: 8,
              display: 'flex', justifyContent: 'space-between', alignItems: 'center', zIndex: 3
            }}>
              <div style={{
                background: 'rgba(0, 0, 0, 0.75)',
                backdropFilter: 'blur(8px)',
                border: `1px solid ${accentColor}66`,
                color: accentColor,
                fontSize: 9, fontWeight: 900,
                padding: '3px 8px', borderRadius: 6,
                letterSpacing: '0.6px', textTransform: 'uppercase'
              }}>
                ● {v.category || `LESSON 0${delay}`}
              </div>

              <div style={{
                background: 'rgba(0, 0, 0, 0.75)',
                backdropFilter: 'blur(8px)',
                border: '1px solid rgba(255,255,255,0.2)',
                color: '#ffffff',
                fontSize: 9, fontWeight: 800,
                padding: '3px 7px', borderRadius: 6,
                display: 'flex', alignItems: 'center', gap: 4
              }}>
                <span>⏱️</span> {v.duration || '4:30'} MIN
              </div>
            </div>

            {/* Central Graphic Icon with Glow */}
            <div style={{
              zIndex: 2,
              transform: hovered ? 'scale(1.12)' : 'scale(1)',
              transition: 'transform 0.3s ease',
              filter: `drop-shadow(0 4px 12px ${accentColor}66)`
            }}>
              <LessonGraphic id={v.id} />
            </div>

            {/* Center Floating Glassmorphic Play Button Overlay */}
            <div style={{
              position: 'absolute', inset: 0, zIndex: 4,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              background: hovered ? 'rgba(0, 0, 0, 0.35)' : 'rgba(0, 0, 0, 0.15)',
              transition: 'background 0.25s'
            }}>
              <div style={{
                width: 42, height: 42, borderRadius: '50%',
                background: hovered
                  ? `linear-gradient(135deg, ${accentColor}, #ffffff)`
                  : 'rgba(255, 255, 255, 0.92)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                color: hovered ? '#000000' : '#0f172a',
                fontSize: 16, fontWeight: 900,
                paddingLeft: 3,
                boxShadow: `0 0 24px ${accentColor}, 0 4px 12px rgba(0,0,0,0.5)`,
                transform: hovered ? 'scale(1.15)' : 'scale(1)',
                transition: 'all 0.25s ease'
              }}>
                ▶
              </div>
            </div>

            {/* Bottom Scrim & Status Badge */}
            <div style={{
              position: 'absolute', bottom: 0, left: 0, right: 0, height: 40,
              background: 'linear-gradient(to top, rgba(0,0,0,0.85) 0%, transparent 100%)',
              zIndex: 2, display: 'flex', alignItems: 'flex-end', justifyContent: 'flex-end',
              padding: '6px 8px'
            }}>
              {watched ? (
                <div style={{
                  background: 'linear-gradient(135deg, #10b981, #059669)', color: '#ffffff',
                  fontSize: 9, fontWeight: 900, padding: '2px 8px', borderRadius: 999,
                  boxShadow: '0 2px 8px rgba(16,185,129,0.5)', display: 'flex', alignItems: 'center', gap: 4
                }}>
                  <span>✓</span> WATCHED
                </div>
              ) : (
                <div style={{
                  background: 'rgba(255, 255, 255, 0.2)', backdropFilter: 'blur(4px)',
                  color: '#ffffff', fontSize: 9, fontWeight: 800, padding: '2px 8px', borderRadius: 999,
                  display: 'flex', alignItems: 'center', gap: 4, border: '1px solid rgba(255,255,255,0.3)'
                }}>
                  <span>▶</span> WATCH NOW
                </div>
              )}
            </div>
          </div>

          <h3 style={{ fontWeight: 800, fontSize: 14, color: 'var(--heading-color, #ffffff)', marginBottom: 4, lineHeight: 1.3 }}>{v.title}</h3>
          <p style={{ fontSize: 11, color: 'var(--text-sub, #94a3b8)', fontWeight: 500, marginBottom: 12, lineHeight: 1.4 }}>{v.subtitle}</p>
        </div>

        {/* Footer Badges & Buttons */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 6, flexWrap: 'wrap' }}>
          <div style={{
            background: 'rgba(56, 189, 248, 0.12)', border: '1px solid rgba(56, 189, 248, 0.4)',
            color: '#38bdf8', fontSize: 9, fontWeight: 900, padding: '4px 8px', borderRadius: 999
          }}>
            {watched ? '⭐ +30 XP EARNED' : '⭐ +30 XP REWARD'}
          </div>

          <button
            onClick={(e) => {
              e.stopPropagation()
              setShowTakeaway(true)
            }}
            style={{
              background: 'rgba(245, 158, 11, 0.15)',
              border: '1px solid #f59e0b',
              color: '#fbbf24',
              fontSize: 10,
              fontWeight: 800,
              borderRadius: 8,
              padding: '4px 10px',
              cursor: 'pointer'
            }}
          >
            📖 NOTES
          </button>
        </div>
      </div>

      {/* Projector Video Player Modal */}
      {showPlayer && (
        <div style={{
          position: 'fixed', inset: 0, background: 'rgba(8, 7, 5, 0.88)',
          zIndex: 999, display: 'flex', flexDirection: 'column',
          backdropFilter: 'blur(16px)',
          fontFamily: "'Space Grotesk', sans-serif",
        }} onClick={() => setShowPlayer(false)}>
          
          {/* Header */}
          <div style={{
            padding: '16px 24px',
            background: '#12100c',
            borderBottom: '1.5px solid rgba(217, 119, 6, 0.3)',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          }} onClick={e => e.stopPropagation()}>
            <div style={{ color: '#ffffff', fontWeight: 800, fontSize: 17, display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 18, color: '#f59e0b' }}>🎬</span>
              {v.title}
            </div>
            <button onClick={() => setShowPlayer(false)} className="btn-outline" style={{ padding: '6px 16px', fontSize: 12 }}>
              ✕ CLOSE CLASSROOM
            </button>
          </div>
          
          {/* Main Classroom Area */}
          <div style={{
            flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
            backgroundImage: "url('/scenes/classroom.png')",
            backgroundSize: 'cover', backgroundPosition: 'center',
            padding: '20px', position: 'relative',
          }} onClick={e => e.stopPropagation()}>
            <div style={{ position: 'absolute', inset: 0, background: 'rgba(8, 7, 5, 0.6)' }} />
            
            {/* NPC Speech Bubble with active AI Guide */}
            <div style={{
              position: 'relative', zIndex: 10, marginBottom: 12,
              background: '#12100c', border: '2px solid #f59e0b',
              borderRadius: 16, padding: '12px 20px', maxWidth: 640, width: '100%',
              boxShadow: '0 10px 25px rgba(0,0,0,0.6)',
              display: 'flex', alignItems: 'center', gap: 14,
            }}>
              <div style={{ fontSize: 32 }}>{activeAvatar?.icon || '👩‍🏫'}</div>
              <div>
                <div style={{ fontSize: 11, fontWeight: 900, color: '#fbbf24', textTransform: 'uppercase' }}>
                  CLASSROOM MENTOR · {guideName.toUpperCase()}
                </div>
                <div style={{ fontSize: 13, fontWeight: 700, color: '#ffffff' }}>
                  "Welcome class! Watch this projector lesson on <strong>{v.title}</strong> to earn +30 XP!"
                </div>
              </div>
            </div>

            {/* Framed Projector Screen */}
            <div style={{
              position: 'relative', zIndex: 10,
              maxWidth: '920px', width: '100%',
              background: '#000000', borderRadius: 20,
              border: '4px solid #d97706',
              boxShadow: '0 20px 50px rgba(0,0,0,0.8), 0 0 30px rgba(245,158,11,0.3)',
              overflow: 'hidden',
            }}>
              {isDraft ? (
                <div style={{
                  padding: 50, color: 'white', textAlign: 'center',
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14,
                }}>
                  <span style={{ fontSize: 64 }}>🚀</span>
                  <h3 className="font-display" style={{ fontSize: 28, color: '#f59e0b', margin: 0 }}>LESSON IN PRODUCTION!</h3>
                  <p style={{ fontSize: 13, color: '#d1d5db', maxWidth: 400, fontWeight: 600 }}>
                    This video lesson is being crafted. Click below to claim +30 XP and unlock your quiz!
                  </p>
                </div>
              ) : (
                <video
                  key={v.id}
                  src={v.src}
                  controls
                  autoPlay
                  preload="auto"
                  style={{ width: '100%', maxHeight: '60vh', display: 'block' }}
                  onEnded={handleVideoEnd}
                  onTimeUpdate={handleTimeUpdate}
                />
              )}
            </div>
          </div>

          {/* Footer CTA */}
          <div style={{
            padding: '16px 24px',
            background: '#12100c',
            borderTop: '1.5px solid rgba(217, 119, 6, 0.3)',
            display: 'flex', justifyContent: 'center', alignItems: 'center'
          }} onClick={e => e.stopPropagation()}>
            {!watched && (
              <button
                disabled={!canMarkWatched}
                onClick={handleMarkWatched}
                className={canMarkWatched ? 'btn-primary' : 'btn-outline'}
                style={{
                  fontSize: 14, padding: '12px 32px',
                  opacity: canMarkWatched ? 1 : 0.6,
                  cursor: canMarkWatched ? 'pointer' : 'not-allowed',
                }}
              >
                {canMarkWatched 
                  ? (isDraft ? '⏭️ SKIP DRAFT LESSON & CLAIM +30 XP' : '✅ MARK AS WATCHED & CLAIM +30 XP')
                  : '⏳ WATCH 85% OF VIDEO TO COMPLETE'
                }
              </button>
            )}
          </div>
        </div>
      )}

      {/* Takeaway Modal */}
      {showTakeaway && <TakeawayModal video={v} onClose={() => setShowTakeaway(false)} />}
    </>
  )
}

export default function BeginnerLevel({ go, goBack, state, update, addXP, aiGuideAvatar = 'female', aiGuideName, onChatToggle }) {
  const activeAvatar = AI_AVATARS[aiGuideAvatar] || AI_AVATARS.female
  const guideName = aiGuideName || activeAvatar.name
  const watched = state.lessonsWatched || []
  const total = VIDEO_FILES.length
  const [activeTab, setActiveTab] = useState('classroom') // 'classroom' | 'lessons' | 'takeaways'

  const isIntermediateStart = state.startingLevel === 'intermediate'
  const begCleared = (isIntermediateStart && (state.quizScore || 0) >= 60) || ((state.lessonsWatched || []).length >= 4 && (state.quizScore || 0) >= 60)
  const progress = begCleared ? total : Math.min(watched.length, total)
  const progressPct = begCleared ? 100 : Math.min(100, Math.round((progress / total) * 100))

  const handleWatch = (id) => {
    if (!watched.includes(id)) {
      const newWatched = [...watched, id]
      update({ lessonsWatched: newWatched })
      addXP(30)
    }
  }

  return (
    <div className="content-area" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>
      
      {/* Top Back Action Bar */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <button
          onClick={goBack || (() => go('landing'))}
          style={{
            background: 'var(--bg-card, rgba(18, 16, 12, 0.9))',
            border: '1.5px solid rgba(217, 119, 6, 0.4)',
            color: 'var(--gold-amber, #fbbf24)',
            borderRadius: 999,
            padding: '8px 18px',
            fontSize: 12,
            fontWeight: 900,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            boxShadow: '0 4px 14px rgba(0,0,0,0.4)',
            transition: 'all 0.2s'
          }}
        >
          <span>⬅</span>
          <span>Back to Main Page</span>
        </button>
      </div>

      {/* ─── 3D SCHOOL ENTRANCE BUILDING BACKGROUND SCENE ─── */}
      <div style={{
        position: 'relative',
        width: '100%',
        minHeight: '520px',
        borderRadius: 24,
        overflow: 'hidden',
        border: '2px solid rgba(217, 119, 6, 0.4)',
        boxShadow: 'var(--card-shadow, 0 20px 50px rgba(0,0,0,0.8))',
        marginBottom: 24,
        backgroundImage: "url('/scenes/classroom.png')",
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        display: 'flex',
        flexDirection: 'column',
        justify: 'space-between',
        padding: '24px'
      }}>
        {/* Ambient Dark Overlay */}
        <div style={{ position: 'absolute', inset: 0, background: 'rgba(8, 7, 5, 0.45)', pointerEvents: 'none' }} />

        {/* Top Floating Row: Right Task Panel */}
        <div style={{ position: 'relative', zIndex: 10, display: 'flex', justifyContent: 'flex-end', alignItems: 'flex-start', flexWrap: 'wrap', gap: 16 }}>
          {/* Level 1 Progress & Task List */}
          <div style={{
            background: 'var(--bg-card, rgba(18, 16, 12, 0.92))',
            backdropFilter: 'blur(16px)',
            border: '1.5px solid rgba(217, 119, 6, 0.35)',
            borderRadius: 20,
            padding: '18px 22px',
            width: 280,
            boxShadow: '0 12px 32px rgba(0,0,0,0.6)'
          }}>
            <div style={{ fontSize: 10, fontWeight: 900, color: '#38bdf8', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>
              LEVEL 1 PROGRESS
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 14 }}>
              <div style={{
                width: 54, height: 54, borderRadius: '50%',
                background: 'conic-gradient(#10b981 0% ' + progressPct + '%, rgba(255,255,255,0.1) ' + progressPct + '% 100%)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                padding: 4
              }}>
                <div style={{
                  width: '100%', height: '100%', borderRadius: '50%',
                  background: 'var(--bg-main, #080705)', display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 12, fontWeight: 900, color: '#10b981'
                }}>
                  {progressPct}%
                </div>
              </div>
              <div>
                <div style={{ fontSize: 13, fontWeight: 900, color: 'var(--heading-color, #ffffff)' }}>
                  {progress} of {total} Lessons
                </div>
                <div style={{ fontSize: 10, color: 'var(--text-muted, #94a3b8)', fontWeight: 700 }}>
                  Completed
                </div>
              </div>
            </div>

            <div style={{ fontSize: 11, fontWeight: 800, color: '#fbbf24', marginBottom: 6 }}>YOUR TASKS:</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4, fontSize: 11 }}>
              {VIDEO_FILES.map((v, idx) => {
                const isW = begCleared || watched.includes(v.id)
                return (
                  <div key={v.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: isW ? '#6ee7b7' : 'var(--text-muted, #94a3b8)' }}>
                    <span>🎬 {v.title}</span>
                    <span>{isW ? '✓' : '🔒'}</span>
                  </div>
                )
              })}
            </div>
          </div>
        </div>

        {/* Center Building Banner */}
        <div style={{ position: 'relative', zIndex: 10, textAlign: 'center', margin: '20px 0' }}>
          <div className="sticker-badge sticker-yellow" style={{ marginBottom: 6 }}>
            LEARN • UNDERSTAND • GROW
          </div>
          <h1 className="font-display" style={{ fontSize: 38, color: '#ffffff', textShadow: '0 4px 20px rgba(0,0,0,0.8)' }}>
            LEARN2INVEST SCHOOL
          </h1>
        </div>

        {/* Bottom Floating Interactive Circular Buttons */}
        <div style={{
          position: 'relative', zIndex: 10,
          display: 'flex', justifyContent: 'center', alignItems: 'center',
          gap: 16, flexWrap: 'wrap'
        }}>
          {/* CLASSROOM */}
          <button
            onClick={() => setActiveTab('classroom')}
            style={{
              width: 80, height: 80, borderRadius: '50%',
              background: activeTab === 'classroom' ? 'linear-gradient(135deg, #10b981, #0284c7)' : 'rgba(18, 16, 12, 0.9)',
              border: activeTab === 'classroom' ? '3px solid #ffffff' : '2px solid #10b981',
              color: '#ffffff', cursor: 'pointer',
              display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
              boxShadow: activeTab === 'classroom' ? '0 0 24px #10b981' : '0 8px 20px rgba(0,0,0,0.5)',
              transition: 'all 0.25s'
            }}
          >
            <span style={{ fontSize: 24 }}>🎓</span>
            <span style={{ fontSize: 9, fontWeight: 900, marginTop: 2 }}>CLASSROOM</span>
          </button>

          {/* LESSONS */}
          <button
            onClick={() => setActiveTab('lessons')}
            style={{
              width: 80, height: 80, borderRadius: '50%',
              background: activeTab === 'lessons' ? 'linear-gradient(135deg, #d97706, #f59e0b)' : 'rgba(18, 16, 12, 0.9)',
              border: activeTab === 'lessons' ? '3px solid #ffffff' : '2px solid #f59e0b',
              color: '#ffffff', cursor: 'pointer',
              display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
              boxShadow: activeTab === 'lessons' ? '0 0 24px #f59e0b' : '0 8px 20px rgba(0,0,0,0.5)',
              transition: 'all 0.25s'
            }}
          >
            <span style={{ fontSize: 24 }}>📖</span>
            <span style={{ fontSize: 9, fontWeight: 900, marginTop: 2 }}>LESSONS</span>
          </button>

          {/* ACHIEVEMENTS */}
          <button
            onClick={() => go('level-map')}
            style={{
              width: 80, height: 80, borderRadius: '50%',
              background: 'rgba(18, 16, 12, 0.9)',
              border: '2px solid #38bdf8',
              color: '#ffffff', cursor: 'pointer',
              display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
              boxShadow: '0 8px 20px rgba(0,0,0,0.5)',
              transition: 'all 0.25s'
            }}
          >
            <span style={{ fontSize: 24 }}>🏆</span>
            <span style={{ fontSize: 9, fontWeight: 900, marginTop: 2 }}>MAP</span>
          </button>
        </div>
      </div>

      {/* ─── ACTIVE TAB CONTENT (LESSONS GRID / CLASSROOM) ─── */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <h2 style={{ fontSize: 22, color: 'var(--heading-color, #ffffff)', margin: 0, fontWeight: 900 }}>
            {activeTab === 'lessons' ? '📖 ALL SCHOOL LESSONS' : '🎓 INTERACTIVE CLASSROOM LESSONS'}
          </h2>
          <div className="sticker-badge sticker-yellow">
            ⭐ {state.xp} XP EARNED
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: 14 }}>
          {VIDEO_FILES.map((i, idx) => (
            <VideoCard
              key={i.id}
              v={i}
              watched={watched.includes(i.id)}
              onWatch={handleWatch}
              delay={idx + 1}
              activeAvatar={activeAvatar}
              guideName={guideName}
            />
          ))}
        </div>
      </div>

      <div style={{ display: 'flex', gap: 12, marginTop: 24 }}>
        <button className="btn-outline" onClick={() => go('level-map')}>← BACK TO CAMPUS MAP</button>
      </div>
    </div>
  )
}
